### ISSUE TITLE
해결 방법

### ISSUE THREAD

**Issue by ParkSangSun1** [CLOUDoort/helpme#1]
- File -> New -> Image Asset 클릭 -> 기본 사진으로 NEXT -> FINISH
- Clean project/ Rebuild
- 메니페스트에 icon을
```
        android:icon="@mipmap/ic_launcher"
```
후에 빌드하시면 성공적으로 빌드가 됩니다!

**Comment by CLOUDoort** [comment]
감사합니다!

**Comment by ParkSangSun1** [comment]
이슈를 닫겠습니다
